tunnel: 63836ec8-7813-4234-9858-69ae70a1c5e7
credentials-file: /etc/cloudflared/63836ec8-7813-4234-9858-69ae70a1c5e7.json

ingress:
  - hostname: radiant-core.com
    service: http://radiant_frontend:5173
  - hostname: api.radiant-core.com
    service: http://codex_api:3200
  - hostname: gateway.radiant-core.com
    service: http://ai_gateway:3600
  - hostname: tts.radiant-core.com
    service: http://ai_api:3300
  - hostname: stt.radiant-core.com
    service: http://stt_ws:3100
  - hostname: ai.radiant-core.com
    service: http://xtts_speaker:3700
  - service: http_status:404