tunnel: 135188d3-3fcc-424a-b48a-3e84e0f3f3b8
credentials-file: /mnt/d/RadiantCore/cloudflared/.cloudflared/135188d3-3fcc-424a-b48a-3e84e0f3f3b8.json

ingress:
  - hostname: radiant-core.com
    service: http://radiant_frontend:5173
  - hostname: api.radiant-core.com
    service: http://codex_api:3200
  - hostname: gateway.radiant-core.com
    service: http://ai_gateway:3600
  - hostname: tts.radiant-core.com
    service: http://xtts_speaker:3300
  - hostname: stt.radiant-core.com
    service: http://stt_ws:3100
  - hostname: ai.radiant-core.com
    service: http://ai_api:3700
  - service: http_status:404